#!/bin/bash

echo "Welcome to Chakora's module retriever"
echo "Just sit back and relax for now, this will take a bit"

yes | cpan -if Term::Prompt IO::Socket Sub::Delete Getopt::Long Term::ANSIColor Config::Scoped File::Data Digest::Whirlpool Digest::HMAC Email::Valid

echo "Modules installed"
echo "Thanks for using Chakora :)"
